apiVersion: v1
kind: Service
metadata:
  name: weight-converter-service
spec:
  type: NodePort
  selector:
    app: weight-converter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
